name: Build Electron App

on:
  push

jobs:
  build-on-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install and Build
      run: yarn && yarn dist

    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: dist/*.exe
